server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: vacancies
          uri:
            http://localhost:8089
          predicates:
            - Path=/vacancies
          filters:
            - SetPath=/api/v1/vacancies/
            - JwtAuthenticationFilter
