server:
  port: 8085

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
              - HEAD
        add-to-simple-url-handler-mapping: true
      routes:
        - id: getUserDetailsByEmail
          uri:
            http://localhost:8089
          predicates:
            - Path=/userDetails/{email}
            - Method=GET
          filters:
            - SetPath=/api/v1/userDetails/email/{email}
        - id: createCandidate
          uri:
            http://localhost:8089
          predicates:
            - Path=/candidates
            - Method=POST
          filters:
            - SetPath=/api/v1/candidates
        - id: createEmployer
          uri:
            http://localhost:8089
          predicates:
            - Path=/employers
            - Method=POST
          filters:
            - SetPath=/api/v1/employers
        - id: getVacancies
          uri:
            http://localhost:8089
          predicates:
            - Path=/vacancies
            - Method=GET
          filters:
            - SetPath=/api/v1/vacancies
            - JwtAuthenticationFilter
        - id: getVacancyById
          uri:
            http://localhost:8089
          predicates:
            - Path=/vacancies/{id}
            - Method=GET
          filters:
            - SetPath=/api/v1/vacancies/{id}
            - JwtAuthenticationFilter
        - id: createVacancy
          uri:
            http://localhost:8089
          predicates:
            - Path=/vacancies
            - Method=POST
          filters:
            - SetPath=/api/v1/vacancies
            - JwtAuthenticationFilter
        - id: updateVacancy
          uri:
            http://localhost:8089
          predicates:
            - Path=/vacancies/{id}
            - Method=PUT
          filters:
            - SetPath=/api/v1/vacancies/{id}
            - JwtAuthenticationFilter
        - id: deleteVacancy
          uri:
            http://localhost:8089
          predicates:
            - Path=/vacancies/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/v1/vacancies/{id}
            - JwtAuthenticationFilter
        - id: register
          uri:
            http://localhost:8080
          predicates:
            - Path=/register
          filters:
            - SetPath=/auth/register
        - id: authenticate
          uri:
            http://localhost:8080
          predicates:
            - Path=/authenticate
          filters:
            - SetPath=/auth/authenticate
